agency/urls.py
from django.urls import path

from agency.views import (
    index,
    about,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspapersDetailView,
    NewspapersCreateView,
    NewspapersUpdateView,
    NewspapersDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("about", about, name="about"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create"
    ),
    path(
        "topics/<int:pk>/update",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list"
    ),
    path(
        "newspapers/<int:pk>",
        NewspapersDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create",
        NewspapersCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update",
        NewspapersUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete",
        NewspapersDeleteView.as_view(),
        name="newspaper-delete"
    ),

    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),

    path(
        "redactors/<int:pk>",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/delete",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),

]

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agency/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=False)
    REQUIRED_FIELDS = ["years_of_experience", ]

    class Meta:
        ordering = ["username"]
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("agency:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255, unique=True)
    context = models.TextField(blank=False)
    published_date = models.DateField(auto_now=True)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
    )
    publishers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="newspapers"
    )

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return f"{self.title} {self.context} ({self.published_date})"

    def get_absolute_url(self):
        return reverse("agency:newspaper-detail", kwargs={"pk": self.pk})

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from agency.models import Redactor, Newspaper


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class RedactorExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["years_of_experience"]


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": 'Search by title...'}),
        label=""
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": 'Search by username...'}),
        label=""
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": 'Search by name...'}),
        label=""
    )

agency/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from agency.forms import RedactorCreationForm, RedactorExperienceUpdateForm, NewspaperForm, NewspaperSearchForm, \
    RedactorSearchForm, TopicSearchForm
from agency.models import Redactor, Newspaper, Topic


@login_required
def index(request):
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_publishers": Redactor.objects.count(),
        "num_newspapers": Newspaper.objects.count(),
        "num_topics": Topic.objects.count(),
        "num_visits": num_visits + 1,
        }

    return render(request, "agency/index.html", context=context)


@login_required
def about(requests):
    return render(requests, "agency/about.html")


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    template_name = "agency/topic_list.html"
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Topic.objects.all()

        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
               name__icontains=form.cleaned_data["name"]
            )

        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    template_name = "agency/topic_confirm_delete.html"
    success_url = reverse_lazy("agency:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    template_name = "agency/newspaper_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")

        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return queryset


class NewspapersDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspapersCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm


class NewspapersUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm


class NewspapersDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    template_name = "agency/newspaper_confirm_delete.html"
    success_url = reverse_lazy("agency:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    template_name = "agency/redactor_list.html"
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()

        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    template_name = "agency/redactor_form.html"


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorExperienceUpdateForm
    success_url = reverse_lazy("agency:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("agency:redactor-list")

templates/agency/about.html
{% extends "base.html" %}

{% block title %}<title>About | Newspaper Agency</title>{% endblock %}

{% block content %}
  <div class="row" style="height: 100%">
    <h2 class="text-dark pt-3 mt-n5 border border-dark text-xxl-center">
      NewspaperAgency
    </h2>
  </div>
  <br>
  <p style= "text-indent: 3%" >Newspapers are an important part of the life of modern society, but they are being replaced more and more by the Internet, which has both positive and negative results.</p>
  <p style= "text-indent: 3%">For modern society, high-quality and timely information is one of the main values. Its creation and dissemination is a function of the mass media, among which one of the most ancient is the periodical press.
    The role of newspapers and magazines in the life of society is enormous. Magazines, newspapers, popular science and fiction are the main means of storing and transmitting from generation to generation all the achievements of science and culture.
    For people of all ages, magazines and newspapers serve as a source of knowledge, help to learn and appreciate life, understand the laws of social relations and natural phenomena.</p>
  <div >Information update: {% now "jS F Y H:i" %}</div>
{% endblock %}

templates/agency/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}<title>Home | Newspaper Agency</title>{% endblock %}

{% block content %}
  <header class="header-2">
  <div class="page-header min-vh-75 relative">
    <span class="mask bg-gradient-primary bg-gradient opacity-4"></span>
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-dark pt-3 mt-n5 border border-dark text-xxl-center">NewspaperAgency</h1>
          <p class="text-md-center lead text-dark mt-2 ">If you love a writer, do not miss the opportunity to get acquainted with his letters and diaries, this will allow you to better, deeper understand him, the person and friend whom you have already known and loved through his books<br/></p>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

<section class="pt-3 pb-4" id="count-stats">
  <div class="container bg-light ">
    <div class="row">
      <div class="col-lg-9 mx-auto py-3">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state1" >{{ num_topics }}</span>+</h1>
              <h5 class="mt-3">Number of topics: </h5>
              <p class="text-sm font-weight-normal">Topic: What is this piece about? it's a circle of problems</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"> <span id="state2"> {{ num_newspapers }} </span>+</h1>
              <h5 class="mt-3">Number of newspapers:</h5>
              <p class="text-sm font-weight-normal">Only the great masters of style manage to be unreadable.</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"> <span id="state2"> {{ num_publishers }} </span>+</h1>
              <h5 class="mt-3">Numbers of publishers: </h5>
              <p class="text-sm font-weight-normal">A book that is well written always seems too short to me.</p>
            </div>
            <hr class="vertical dark">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
</div>
{% endblock %}

templates/agency/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete article {{ newspaper.title }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-outline-secondary" href="{% url 'agency:newspaper-list' %}"> Cancel </a>
  </form>
{% endblock %}

templates/agency/newspaper_detail.html
{% extends "base.html" %}

{% block title %}<title>Articles | NewspaperAgency</title>{% endblock %}

  {% block content %}
    <h1 class=" text-xl-center">{{ newspaper.title }}

    </h1>
    <h3>{{ newspaper.topic.name }}, {{ newspaper.published_date }}</h3>
    <p>{{ newspaper.context }}</p>

    <br>
      {% for publiser in newspaper.publishers.all %}
      <li>{{ publiser.username }} ({{ publiser.first_name }} {{ publiser.last_name }})</li>
    {% endfor %}
      <br>
      <a class="btn btn-outline-danger" href="{% url 'agency:newspaper-delete' pk=newspaper.id%}"> Delete </a>
      <a class="btn btn-outline-primary" href="{% url 'agency:newspaper-update' pk=newspaper.id%}"> Update </a>
      <a class="btn btn-outline-secondary" href="{% url 'agency:newspaper-list' %}"> Back </a>

  {% endblock %}

templates/agency/newspaper_form.html
{% extends "base.html" %}

{% block title %}<title>Edit | NewspaperAgency</title>{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} article {{ newspaper.title }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

  <div>
    <input type="submit" value="Submit" class="btn btn-primary">
    <a class="btn btn-outline-secondary" href="{% url 'agency:newspaper-list' %}"> Back </a>
  </div>
  </form>
{% endblock %}

templates/agency/newspaper_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}<title>Newspaper | NewspaperAgency</title>{% endblock %}

{% block content %}

  <h1 class="text-xxl-center">
    <div class="p-3 mb-2 border border-dark ">Topical articles</div>
  </h1>
  <br>
  {% if newspaper_list  %}
    {% for newspaper in newspaper_list %}
      <div class="card bg-dark text-dark">
        <img src="{% static 'img/gray_fon.jpeg' %}" class="card-img p-7 bg-gradient" style="max-height: 150px" alt="Art">
        <div class="card-img-overlay">
          <h5 class="card-title ">{{ newspaper.title }}</h5>
          <p class="card-text"><small class="text-dark ">({{ newspaper.topic.name }} - {{ newspaper.published_date }})</small></p>
          <p class="card-text"><a type="button" class="btn btn-primary btn-sm" href="{{ newspaper.get_absolute_url }}"> Read more >>> </a></p>
        </div>
      </div>
      <br>
    {% endfor %}
  {% else %}
    <p>There are no articles</p>
  {% endif %}
  <br>
    <div>
      <a class="btn btn-outline-primary" href="{% url 'agency:newspaper-create' %}"> Create </a>
      <a class="btn btn-outline-secondary" href="{% url 'agency:index' %}"> Back </a>
    </div>

{% endblock %}

templates/agency/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete publisher {{ redactor.username }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-outline-secondary" href="{% url 'agency:redactor-detail' pk=redactor.id %}"> Cancel </a>
  </form>
{% endblock %}

templates/agency/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Username: {{ redactor.username }}</h1>

  <p><strong>First name:</strong> {{ redactor.first_name }}</p>
  <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

  {% for newspaper in redactor.newspapers.all %}
        <hr>
        <p><strong>Title:</strong> {{ newspaper.title }}</p>
        <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{newspaper.id}}</p>

    {% empty %}
      <p>No Publishers</p>
    {% endfor %}
  <div>
    <a class="btn btn-outline-primary" href="{% url 'agency:redactor-update' pk=redactor.id%}"> Edit </a>
    <a class="btn btn-outline-danger" href="{% url 'agency:redactor-delete' pk=redactor.id%}"> Delete </a>
    <a class="btn btn-outline-secondary" href="{% url 'agency:redactor-list' %}"> Back </a>
  </div>
{% endblock %}

templates/agency/redactor_form.html
{% extends "base.html" %}

{% block title %}<title>Edit | NewspaperAgency</title>{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} publisher {{ redactor.username }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a class="btn btn-outline-secondary" href="{% url 'agency:redactor-list' %}">Back</a>
  </form>
{% endblock %}

templates/agency/redactor_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}<title>Publishers | NewspaperAgency</title>{% endblock %}

{% block content %}
  <h1 class="text-xxl-center" >
    <div class="p-3 mb-2 border border-dark ">Publishers</div>
  </h1>
  <br>
  {% if redactor_list %}

      {% for redactor in redactor_list %}
        <div class="card bg-dark text-dark">
          <img src="{% static 'img/gray_fon.jpeg' %}" class="card-img p-7 bg-gradient" style="max-height: 150px" alt="Art">
            <div class="card-img-overlay">
              <h5 class="card-title ">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</h5>
            <p class="card-text"><small class="text-dark ">({{ redactor.first_name }} {{ redactor.last_name }})</small></p>
              <p class="card-text "><a type="button" class="btn btn-primary btn-sm" href="{% url 'agency:redactor-detail' pk=redactor.id %}">About >>></a></p>
          </div>
        </div>
        <br>
      {% endfor %}
  {% else %}
    <p>There are no publishers</p>
  {% endif %}
  <br>
<div>
  <a class="btn btn-outline-primary" href="{% url 'agency:redactor-create' %}">Create</a>
  <a class="btn btn-outline-secondary" href="{% url 'agency:index' %}">Back</a>
</div>
{% endblock %}

templates/agency/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic {{ topic.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-outline-secondary" href="{% url 'agency:topic-list' %}"> Cancel </a>
  </form>
{% endblock %}

templates/agency/topic_form.html
{% extends "base.html" %}

{% block title %}<title>Edit | NewspaperAgency</title>{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} topic {{ topic.name }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a class="btn btn-outline-secondary" href="{% url 'agency:topic-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/agency/topic_list.html
{% extends "base.html" %}

{% block title %}<title>Topics | NewspaperAgency</title>{% endblock %}

{% block content %}
  <h1 class="p-3 mb-2 border border-dark text-xxl-center">Topics</h1>

  <table class="table">
     {% if topic_list %}
    {% for topic in topic_list %}
   <tbody>
      <td>{{ topic.name }}</td>
      <td></td>
      <td><a class="btn btn-outline-danger" href="{% url 'agency:topic-delete' pk=topic.id%}">Delete</a></td>
    {% endfor %}

  {% else %}
    <p>There are no topics</p>
  {% endif %}

  </tbody>
</table>
  <br>
  <a class="btn btn-outline-primary" href="{% url 'agency:topic-create' %}">Create</a>
  <a class="btn btn-outline-secondary" href="{% url 'agency:index' %}">Back</a>
{% endblock %}