agency/urls.py
from django.urls import path

from agency.views import (
    index,
    about,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspapersDetailView,
    NewspapersCreateView,
    NewspapersUpdateView,
    NewspapersDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("about", about, name="about"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create"
    ),
    path(
        "topics/<int:pk>/update",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list"
    ),
    path(
        "newspapers/<int:pk>",
        NewspapersDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create",
        NewspapersCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update",
        NewspapersUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete",
        NewspapersDeleteView.as_view(),
        name="newspaper-delete"
    ),

    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),

    path(
        "redactors/<int:pk>",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/delete",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),

]

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<div class="col-12">
  <div class="text-center">
     <p class="text-dark my-4 text-sm font-weight-normal">© Copyright 2023 | NewspaperAgency</p>
   </div>
</div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
    <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">Previous</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'agency:index' %}">NewspaperAgency</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'agency:newspaper-list' %}">All articles</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'agency:topic-list' %}">All topics</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'agency:redactor-list' %}">All publishers</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'agency:about' %}">About</a>
        </li>

        <li class="nav-item dropdown">
          {% if user.is_authenticated %}
            <a class="nav-link dropdown-toggle justify-content-center" href="{{ user.get_absolute_url }}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Username: {{ user.get_username }}
          </a>

          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
          </ul>
          {% else %}
           <li class="nav-item">
             <a class="nav-link align-content-end" href="{% url 'login'%}?next={{request.path}}">Login</a>
           </li>
          {% endif %}
        </ul>

        {% if search_form %}
          <form class="d-flex" role="search" action="" method="get">
            <input class="form-control" type="{{ search_form }}">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        {% endif %}
    </div>
  </div>
</nav>